server.port=8081
spring.application.name=auth-service

spring.datasource.url=jdbc:mysql://localhost:3306/kinal_users_in5am?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=IN5AM
spring.datasource.password=_odmon5Am
# ...
jwt.secret=4qhq8L6M4K2A9X7V3z1Y8r5T0w3E6u9I1o4P7a0S3d6F9g2H5j8K1l4Z7x0C3v6
jwt.expiration= 3600000
application.user-service.url=http://localhost:8082