server.port=8083
spring.application.name=book-service

# Database Config - kinal_books
spring.datasource.url=jdbc:mysql://localhost:3306/kinal_books_in5am?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=IN5AM
spring.datasource.password=_odmon5Am
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret 
jwt.secret=4qhq8L6M4K2A9X7V3z1Y8r5T0w3E6u9I1o4P7a0S3d6F9g2H5j8K1l4Z7x0C3v6
